title: Robert Stohel
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description:
    > # your text below (remove <br> elements if you don't need line breaks)
    <br><br>
    Experienced data and software engineer with over 4 years in building and optimizing data solutions. Proficient in technologies like Azure Synapse Analytics, Azure Fabric, and Spark, as well as programming languages such as Python, R, Java, and SQL. Adept at designing and streamlining data pipelines, with a solid foundation in data structures and algorithms to create efficient software solutions.
    <br><br>
    Proven ability to lead cross-functional teams and deliver scalable solutions that drive business value. Achievements include enhancing processing speeds, optimizing database queries, and managing critical data projects from start to finish. Passionate about continuous learning and adopting new technologies to innovate data processes. Ready to bring technical and collaborative expertise to your team.
    <br><br>
    <a href="https://www.linkedin.com/in/stohel/">View My LinkedIn Profile</a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
    - jekyll-remote-theme
google_analytics: G-HGSR679LDH # your Google Analytics tracking ID here
