title: Robby Stohel
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description:
    > # your text below (remove <br> elements if you don't need line breaks)
    Experienced data and software engineer with over 4 years of expertise in building and optimizing data solutions.
    <br><br>
    Proven ability to design, implement, and streamline complex data pipelines using technologies like Azure Synapse Analytics, Azure Fabric, and Spark. Skilled in Python, R, Java, and SQL, with a strong foundation in data structures and algorithms to drive efficient software solutions. Collaborative and results-driven, with a history of delivering scalable solutions that add measurable business value.
    <br><br>
    Key achievements include developing data infrastructure that improved processing speeds, optimizing database queries for a reduction in resource use, and leading cross-functional teams on critical data projects from concept to delivery.
    <br><br>
    Highly proficient in programming languages, big data technologies, and agile project management. 
    <br><br>
    Passionate about continuous learning and adopting new technologies to refine and innovate data processes.
    <br><br>
    Ready to bring strong technical and collaborative skills to drive impactful results on your team.
    <br><br>
    <a href="https://www.linkedin.com/in/stohel/">View My LinkedIn Profile</a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
    - jekyll-remote-theme
google_analytics: G-HGSR679LDH # your Google Analytics tracking ID here
